name: Codeowners merging
on:
  pull_request_target: { types: [opened,reopened] }
  issue_comment: { types: [created] }
  pull_request_review: { types: [submitted] }

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: OSS-Docs-Tools/code-owner-self-merge@1.6.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
